[tools]
actionlint = "latest"
delta = "latest"
gh = "latest"
go = "latest"
hadolint = "latest"
neovim = "latest"
node = { version = "lts", postinstall = "corepack false" }
peco = "latest"
pnpm = "latest"
python = "3.13.9"
shfmt = "latest"
task = "latest"
typos = "latest"
usage = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
